### ISSUE TITLE
Use nonce to auth endpoint calls

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/provider-py#13]
- [x] Have initialize endpoint to return a nonce specific per address
- [x] Check nonce on every other endpoint call (except initialize)
- [ ] Update ocean-lib-js to use the nonce from initialize (update createSignature)
- [ ] Update ocean-lib-py to use the nonce from initialize (update createSignature)

Signature becomes createSignature(your_own_address + nonce)

**Comment by ssallam** [comment]
Provider-py implementation is in branch `feature/web3-updates`
